name: py38_playaround-sk_sktime
channels:
  - conda-forge
  - defaults
dependencies:
  - cython=0.29.24
  - fbprophet=0.7.1
  - ipykernel=5.3.4
  - ipython=7.26.0
  - joblib=1.0.1
  - jupyterlab=3.1.4
  - matplotlib=3.4.2
  - notebook=6.4.1
  - pandas=1.3.1
  - pip=21.2.2
  - python=3.8.11
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - sktime=0.7.0
  - sktime-all-extras=0.7.0
  - statsmodels=0.12.2
  - tqdm=4.62.0
  - tsfresh=0.18.0
  - pip:
    - backports-zoneinfo==0.2.1
    - catch22==0.2.0
    - esig==0.9.7 
    - numpy==1.19.5
    - pmdarima==1.8.2
    - setuptools-git==1.2
    - tbats==1.1.0
