name: learn_py38_loguru
channels:
  - defaults
dependencies:
  - flake8=4.0.1
  - isort=5.9.3
  - jupyterlab=3.5.2
  - pip=22.3.1
  - pylint=2.14.5
  - python=3.8.15
  - pip:
      - black==22.12.0
      - loguru==0.6.0
      - rich==12.6.0
