name: learn_py38_pydantic
channels:
  - defaults
dependencies:
  - jupyterlab=3.5.0
  - pip=22.3.1
  - python=3.8.15
  - sqlalchemy=1.4.39
  - pip:
      - black==22.12.0
      - flake8==6.0.0
      - isort==5.11.2
      - mypy==0.991
      - pydantic==1.10.2
      - pylint==2.15.8
