name: learn_py38_hydra
channels:
  - defaults
dependencies:
  - flake8=4.0.1
  - isort=5.9.3
  - jupyterlab=3.5.2
  - pip=22.3.1
  - pylint=2.14.5
  - python=3.8.15
  - pip:
      - black==22.12.0
      - hydra-core==1.3.1
      - mypy==0.991
      - omegaconf==2.3.0
