name: py36_prpy_dash
channels:
  - conda-forge
  - defaults
dependencies:
  - dash=1.17.0
  - numpy=1.19.2
  - pandas=1.1.3
  - pip=20.3
  - plotly=4.13.0
  - python=3.6.12
  - pip:
    - flask-caching==1.9.0
    - redis==3.5.3
